// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: transfer.sql

package db

import (
	"context"
	"database/sql"
)

const createTransfer = `-- name: CreateTransfer :execresult
INSERT INTO transfers (
  to_account_id,
  from_account_id,
  amount
) VALUES (
  $1, $2, $3
)
RETURNING id, to_account_id, from_account_id, amount, create_at
`

type CreateTransferParams struct {
	ToAccountID   int64
	FromAccountID int64
	Amount        int64
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTransfer, arg.ToAccountID, arg.FromAccountID, arg.Amount)
}

const deleteTransfer = `-- name: DeleteTransfer :exec

DELETE FROM transfers
WHERE id = $1
`

// skip many rows
func (q *Queries) DeleteTransfer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransfer, id)
	return err
}

const getTransferByAccountsId = `-- name: GetTransferByAccountsId :one
SELECT id, to_account_id, from_account_id, amount, create_at FROM transfers
WHERE from_account_id = $1 
AND to_account_id = $2
LIMIT 1
`

type GetTransferByAccountsIdParams struct {
	FromAccountID int64
	ToAccountID   int64
}

func (q *Queries) GetTransferByAccountsId(ctx context.Context, arg GetTransferByAccountsIdParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransferByAccountsId, arg.FromAccountID, arg.ToAccountID)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.ToAccountID,
		&i.FromAccountID,
		&i.Amount,
		&i.CreateAt,
	)
	return i, err
}

const getTransferByFromAccountId = `-- name: GetTransferByFromAccountId :one
SELECT id, to_account_id, from_account_id, amount, create_at FROM transfers
WHERE from_account_id = $1 LIMIT 1
`

func (q *Queries) GetTransferByFromAccountId(ctx context.Context, fromAccountID int64) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransferByFromAccountId, fromAccountID)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.ToAccountID,
		&i.FromAccountID,
		&i.Amount,
		&i.CreateAt,
	)
	return i, err
}

const getTransferById = `-- name: GetTransferById :one
SELECT id, to_account_id, from_account_id, amount, create_at FROM transfers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTransferById(ctx context.Context, id int64) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransferById, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.ToAccountID,
		&i.FromAccountID,
		&i.Amount,
		&i.CreateAt,
	)
	return i, err
}

const getTransferByToAccountId = `-- name: GetTransferByToAccountId :one
SELECT id, to_account_id, from_account_id, amount, create_at FROM transfers
WHERE to_account_id = $1 LIMIT 1
`

func (q *Queries) GetTransferByToAccountId(ctx context.Context, toAccountID int64) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransferByToAccountId, toAccountID)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.ToAccountID,
		&i.FromAccountID,
		&i.Amount,
		&i.CreateAt,
	)
	return i, err
}

const listTransfers = `-- name: ListTransfers :many
SELECT id, to_account_id, from_account_id, amount, create_at FROM transfers
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListTransfersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error) {
	rows, err := q.db.QueryContext(ctx, listTransfers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transfer
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.ToAccountID,
			&i.FromAccountID,
			&i.Amount,
			&i.CreateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransfer = `-- name: UpdateTransfer :exec
UPDATE transfers
SET amount = $1 
WHERE id = $2
RETURNING id, to_account_id, from_account_id, amount, create_at
`

type UpdateTransferParams struct {
	Amount int64
	ID     int64
}

func (q *Queries) UpdateTransfer(ctx context.Context, arg UpdateTransferParams) error {
	_, err := q.db.ExecContext(ctx, updateTransfer, arg.Amount, arg.ID)
	return err
}
